name: Check SQL Query Syntax

on: [push]

jobs:
  check-sql-query-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SQL Query Syntax
        run: |
          # Save the SQL query file (replace 'query.sql' with your file name)
          echo "SELECT * FROM [testdb].[dbo].[STUDENTS122]" > query.sql
          
          # Use sqlcmd for syntax checking (without executing)
          sqlcmd -S localhost -d Your_Database_Name -U SA -P 'Your_Strong_Password' -i query.sql -r0
          if [ $? -eq 0 ]; then
            echo "SQL query syntax is valid."
          else
            echo "SQL query syntax is invalid."
            exit 1
          fi
          
      # Add more steps here for your project's build/test/deploy processes
